/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import model.RupiahHelper;



/**
 *
 * @author ASUS
 */
public class FormPenebusan extends javax.swing.JFrame {
    private int idTransaksi;
    
    public FormPenebusan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        Keterangan_txt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Keterangan_TextArea = new javax.swing.JTextArea();
        Batal_btn = new javax.swing.JButton();
        Simpan_btn = new javax.swing.JButton();
        TebusBarang = new java.awt.Label();
        Nama_txt1 = new javax.swing.JLabel();
        Nama_txt2 = new javax.swing.JLabel();
        Nama_txt3 = new javax.swing.JLabel();
        Nama_txt4 = new javax.swing.JLabel();
        Nama_txt5 = new javax.swing.JLabel();
        Nama_txt6 = new javax.swing.JLabel();
        Nama_txt7 = new javax.swing.JLabel();
        Nama_txt8 = new javax.swing.JLabel();
        Nama_txt9 = new javax.swing.JLabel();
        Bunga_textField = new java.awt.TextField();
        Denda_textField = new java.awt.TextField();
        Pinjaman_textField = new java.awt.TextField();
        NamaPenggadai_textField = new java.awt.TextField();
        NamaBarang_textField = new java.awt.TextField();
        Total_textField = new java.awt.TextField();
        TanggalPenebusan_FormattedTextField = new javax.swing.JFormattedTextField();
        TanggalGadai_FormattedTextField1 = new javax.swing.JFormattedTextField();
        JatuhTempo_FormattedTextField2 = new javax.swing.JFormattedTextField();
        Keterangan_txt1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Keterangan_TextArea1 = new javax.swing.JTextArea();
        Batal_btn1 = new javax.swing.JButton();
        Konfirmasi_btn1 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane2);

        Keterangan_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Keterangan_txt.setText("Keterangan");

        Keterangan_TextArea.setColumns(20);
        Keterangan_TextArea.setRows(5);
        jScrollPane1.setViewportView(Keterangan_TextArea);

        Batal_btn.setText("Batal");

        Simpan_btn.setText("Simpan");
        Simpan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpan_btnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TebusBarang.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TebusBarang.setText("Tebus Barang");

        Nama_txt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_txt1.setText("Nama Penggadai");

        Nama_txt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_txt2.setText("Nama Barang");

        Nama_txt3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_txt3.setText("Pinjaman");

        Nama_txt4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_txt4.setText("Tanggal Gadai");

        Nama_txt5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_txt5.setText("Jatuh Tempo");

        Nama_txt6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_txt6.setText("Tanggal Penebusan");

        Nama_txt7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_txt7.setText("Bunga");

        Nama_txt8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_txt8.setText("Denda");

        Nama_txt9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_txt9.setText("Total");

        Bunga_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bunga_textFieldActionPerformed(evt);
            }
        });

        Denda_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Denda_textFieldActionPerformed(evt);
            }
        });

        Pinjaman_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pinjaman_textFieldActionPerformed(evt);
            }
        });

        NamaPenggadai_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPenggadai_textFieldActionPerformed(evt);
            }
        });

        NamaBarang_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaBarang_textFieldActionPerformed(evt);
            }
        });

        Total_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_textFieldActionPerformed(evt);
            }
        });

        TanggalPenebusan_FormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalPenebusan_FormattedTextFieldActionPerformed(evt);
            }
        });

        TanggalGadai_FormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalGadai_FormattedTextField1ActionPerformed(evt);
            }
        });

        JatuhTempo_FormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JatuhTempo_FormattedTextField2ActionPerformed(evt);
            }
        });

        Keterangan_txt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Keterangan_txt1.setText("Keterangan");

        Keterangan_TextArea1.setColumns(20);
        Keterangan_TextArea1.setRows(5);
        jScrollPane3.setViewportView(Keterangan_TextArea1);

        Batal_btn1.setText("Batal");
        Batal_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Batal_btn1ActionPerformed(evt);
            }
        });

        Konfirmasi_btn1.setText("Konfirmasi");
        Konfirmasi_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Konfirmasi_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(TebusBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Nama_txt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nama_txt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nama_txt7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nama_txt8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nama_txt9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nama_txt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nama_txt3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Nama_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Nama_txt2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(22, 22, 22)))
                            .addComponent(Keterangan_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaBarang_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamaPenggadai_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Total_textField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Denda_textField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bunga_textField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TanggalPenebusan_FormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JatuhTempo_FormattedTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TanggalGadai_FormattedTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Pinjaman_textField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Konfirmasi_btn1)
                                            .addGap(18, 18, 18)
                                            .addComponent(Batal_btn1))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(TebusBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nama_txt1)
                    .addComponent(NamaPenggadai_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nama_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaBarang_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nama_txt3)
                    .addComponent(Pinjaman_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TanggalGadai_FormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nama_txt4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama_txt5)
                    .addComponent(JatuhTempo_FormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nama_txt6)
                    .addComponent(TanggalPenebusan_FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nama_txt7)
                            .addComponent(Bunga_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Nama_txt8))
                    .addComponent(Denda_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nama_txt9)
                    .addComponent(Total_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Keterangan_txt1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batal_btn1)
                    .addComponent(Konfirmasi_btn1))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setDataTransaksi(int id, String nama, String barang, double pinjaman, String tglGadai, String jatuhTempo, String keterangan) {
        this.idTransaksi = id;
        NamaPenggadai_textField.setText(nama);
        NamaBarang_textField.setText(barang);
        Pinjaman_textField.setText(RupiahHelper.format(pinjaman));
        TanggalGadai_FormattedTextField1.setText(tglGadai);
        JatuhTempo_FormattedTextField2.setText(jatuhTempo);
        TanggalPenebusan_FormattedTextField.setText(java.time.LocalDate.now().toString());
        Keterangan_TextArea1.setText(keterangan);

        hitungDendaDanTotal();
        
         // Kunci semua field agar tidak bisa diedit
        NamaPenggadai_textField.setEditable(false);
        NamaBarang_textField.setEditable(false);
        Pinjaman_textField.setEditable(false);
        TanggalGadai_FormattedTextField1.setEditable(false);
        JatuhTempo_FormattedTextField2.setEditable(false);
        TanggalPenebusan_FormattedTextField.setEditable(false);
        Keterangan_TextArea1.setEditable(false);
        Bunga_textField.setEditable(false);
        Denda_textField.setEditable(false);
        Total_textField.setEditable(false);
        
         // memberi warna penanda field  tidak bisa diedit
        NamaPenggadai_textField.setBackground(Color.LIGHT_GRAY);
        NamaBarang_textField.setBackground(Color.LIGHT_GRAY);
        Pinjaman_textField.setBackground(Color.LIGHT_GRAY);
        TanggalGadai_FormattedTextField1.setBackground(Color.LIGHT_GRAY);
        JatuhTempo_FormattedTextField2.setBackground(Color.LIGHT_GRAY);
        TanggalPenebusan_FormattedTextField.setBackground(Color.LIGHT_GRAY);
        Keterangan_TextArea1.setBackground(Color.LIGHT_GRAY);
        Bunga_textField.setBackground(Color.LIGHT_GRAY);
        Denda_textField.setBackground(Color.LIGHT_GRAY);
        Total_textField.setBackground(Color.LIGHT_GRAY);
       

    }
    private void hitungDendaDanTotal() {
        try {
            java.time.LocalDate jatuh = java.time.LocalDate.parse(JatuhTempo_FormattedTextField2.getText());
            java.time.LocalDate hariIni = java.time.LocalDate.now();

            long selisihHari = java.time.temporal.ChronoUnit.DAYS.between(jatuh, hariIni);
            double denda = selisihHari > 0 ? selisihHari * 1000 : 0;

            double pinjaman = RupiahHelper.parse(Pinjaman_textField.getText());

            double bunga = pinjaman * 0.05; // 5% bunga
            double total = pinjaman + bunga + denda;

            Denda_textField.setText(RupiahHelper.format(denda));
            Bunga_textField.setText(RupiahHelper.format(bunga));
            Total_textField.setText(RupiahHelper.format(total));

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghitung: " + e.getMessage());
        }
    }

    private void Bunga_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bunga_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bunga_textFieldActionPerformed

    private void Denda_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Denda_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Denda_textFieldActionPerformed

    private void Pinjaman_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pinjaman_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pinjaman_textFieldActionPerformed

    private void NamaPenggadai_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPenggadai_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPenggadai_textFieldActionPerformed

    private void NamaBarang_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaBarang_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaBarang_textFieldActionPerformed

    private void Total_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_textFieldActionPerformed

    private void TanggalPenebusan_FormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalPenebusan_FormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalPenebusan_FormattedTextFieldActionPerformed

    private void TanggalGadai_FormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalGadai_FormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalGadai_FormattedTextField1ActionPerformed

    private void JatuhTempo_FormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JatuhTempo_FormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JatuhTempo_FormattedTextField2ActionPerformed

    private void Simpan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpan_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Simpan_btnActionPerformed

    private void Konfirmasi_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Konfirmasi_btn1ActionPerformed
        try (java.sql.Connection conn = new controller.Koneksi().koneksi();
            java.sql.PreparedStatement ps = conn.prepareStatement("UPDATE transaksi SET status = ?, tanggal_tebus = ?, denda = ?, bunga = ?, total_tebusan = ? WHERE id = ?")) {

            ps.setString(1, "Ditebus");
            ps.setString(2, TanggalPenebusan_FormattedTextField.getText());
            ps.setDouble(3, RupiahHelper.parse(Denda_textField.getText()));
            ps.setDouble(4, RupiahHelper.parse(Bunga_textField.getText()));
            ps.setDouble(5, RupiahHelper.parse(Total_textField.getText()));

            ps.setInt(6, idTransaksi);

            ps.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Barang berhasil ditebus!");
            new DaftarTransaksi().setVisible(true);
            this.dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menebus: " + e.getMessage());
        }
    }//GEN-LAST:event_Konfirmasi_btn1ActionPerformed

    private void Batal_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Batal_btn1ActionPerformed
        new DaftarTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Batal_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenebusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenebusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenebusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenebusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenebusan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal_btn;
    private javax.swing.JButton Batal_btn1;
    private java.awt.TextField Bunga_textField;
    private java.awt.TextField Denda_textField;
    private javax.swing.JFormattedTextField JatuhTempo_FormattedTextField2;
    private javax.swing.JTextArea Keterangan_TextArea;
    private javax.swing.JTextArea Keterangan_TextArea1;
    private javax.swing.JLabel Keterangan_txt;
    private javax.swing.JLabel Keterangan_txt1;
    private javax.swing.JButton Konfirmasi_btn1;
    private java.awt.TextField NamaBarang_textField;
    private java.awt.TextField NamaPenggadai_textField;
    private javax.swing.JLabel Nama_txt1;
    private javax.swing.JLabel Nama_txt2;
    private javax.swing.JLabel Nama_txt3;
    private javax.swing.JLabel Nama_txt4;
    private javax.swing.JLabel Nama_txt5;
    private javax.swing.JLabel Nama_txt6;
    private javax.swing.JLabel Nama_txt7;
    private javax.swing.JLabel Nama_txt8;
    private javax.swing.JLabel Nama_txt9;
    private java.awt.TextField Pinjaman_textField;
    private javax.swing.JButton Simpan_btn;
    private javax.swing.JFormattedTextField TanggalGadai_FormattedTextField1;
    private javax.swing.JFormattedTextField TanggalPenebusan_FormattedTextField;
    private java.awt.Label TebusBarang;
    private java.awt.TextField Total_textField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
