/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.*;
import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author ASUS
 */
public class FormInputTransaksi extends javax.swing.JFrame {

    private int idTransaksi = -1;
    

    public FormInputTransaksi() {
        initComponents();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        TanggalGadai_FormattedTextField.setText(LocalDate.now().format(formatter));
        JatuhTempo_FormattedTextField.setText(LocalDate.now().plusDays(30).format(formatter));
        TanggalGadai_FormattedTextField.setEnabled(false);
        JatuhTempo_FormattedTextField.setEnabled(false);
        
        NamaPenggadai_textField.addActionListener(e -> Kontak_textField.requestFocus());
        Kontak_textField.addActionListener(e -> NamaBarang_textField.requestFocus());
        NamaBarang_textField.addActionListener(e -> Pinjaman_textField.requestFocus());
        Pinjaman_textField.addActionListener(e -> NilaiTaksir_textField.requestFocus());
        NilaiTaksir_textField.addActionListener(e -> Keterangan_TextArea.requestFocus());

    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TambahTransaksi = new javax.swing.JLabel();
        NamaBarang_textField = new java.awt.TextField();
        NamaPenggadai_txt = new javax.swing.JLabel();
        NamaBarang_txt = new javax.swing.JLabel();
        Pinjaman_txt = new javax.swing.JLabel();
        TanggalGadai_txt = new javax.swing.JLabel();
        Nama_txt5 = new javax.swing.JLabel();
        Keterangan_txt = new javax.swing.JLabel();
        Kontak_txt = new javax.swing.JLabel();
        NilaiTaksir_txt = new javax.swing.JLabel();
        NamaPenggadai_textField = new java.awt.TextField();
        Kontak_textField = new java.awt.TextField();
        JatuhTempo_FormattedTextField = new javax.swing.JFormattedTextField();
        TanggalGadai_FormattedTextField = new javax.swing.JFormattedTextField();
        Pinjaman_textField = new java.awt.TextField();
        NilaiTaksir_textField = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Keterangan_TextArea = new javax.swing.JTextArea();
        Batal_btn = new javax.swing.JButton();
        Simpan_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TambahTransaksi.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TambahTransaksi.setText("Tambah Transaksi");

        NamaBarang_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaBarang_textFieldActionPerformed(evt);
            }
        });

        NamaPenggadai_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NamaPenggadai_txt.setText("Nama Penggadai");

        NamaBarang_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NamaBarang_txt.setText("Nama Barang");

        Pinjaman_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pinjaman_txt.setText("Pinjaman");

        TanggalGadai_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TanggalGadai_txt.setText("Tanggal Gadai");

        Nama_txt5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_txt5.setText("Jatuh Tempo");

        Keterangan_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Keterangan_txt.setText("Keterangan");

        Kontak_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kontak_txt.setText("Kontak");

        NilaiTaksir_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NilaiTaksir_txt.setText("Nilai Taksir");

        NamaPenggadai_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPenggadai_textFieldActionPerformed(evt);
            }
        });

        Kontak_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kontak_textFieldActionPerformed(evt);
            }
        });

        JatuhTempo_FormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JatuhTempo_FormattedTextFieldActionPerformed(evt);
            }
        });

        TanggalGadai_FormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalGadai_FormattedTextFieldActionPerformed(evt);
            }
        });

        Pinjaman_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pinjaman_textFieldActionPerformed(evt);
            }
        });

        NilaiTaksir_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiTaksir_textFieldActionPerformed(evt);
            }
        });

        Keterangan_TextArea.setColumns(20);
        Keterangan_TextArea.setRows(5);
        jScrollPane1.setViewportView(Keterangan_TextArea);

        Batal_btn.setText("Batal");
        Batal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Batal_btnActionPerformed(evt);
            }
        });

        Simpan_btn.setText("Simpan");
        Simpan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpan_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(TambahTransaksi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(NilaiTaksir_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Pinjaman_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NamaPenggadai_txt)
                                        .addGap(22, 22, 22))
                                    .addComponent(Kontak_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NamaBarang_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NamaBarang_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NamaPenggadai_textField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Kontak_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                                    .addComponent(Pinjaman_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NilaiTaksir_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Nama_txt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Keterangan_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TanggalGadai_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Simpan_btn)
                                        .addGap(18, 18, 18)
                                        .addComponent(Batal_btn))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(TanggalGadai_FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(JatuhTempo_FormattedTextField)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(TambahTransaksi)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NamaPenggadai_txt)
                                    .addComponent(NamaPenggadai_textField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(Kontak_txt))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Kontak_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NamaBarang_txt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NamaBarang_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Pinjaman_txt)
                    .addComponent(Pinjaman_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NilaiTaksir_txt)
                    .addComponent(NilaiTaksir_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TanggalGadai_txt)
                        .addGap(24, 24, 24)
                        .addComponent(Nama_txt5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Keterangan_txt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TanggalGadai_FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(JatuhTempo_FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batal_btn)
                    .addComponent(Simpan_btn))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDataTransaksi(int id, String nama, String kontak, String barang, double pinjaman, String jatuhTempo, String keterangan, double taksir) {
        this.idTransaksi = id;
        NamaPenggadai_textField.setText(nama);
        Kontak_textField.setText(kontak);
        NamaBarang_textField.setText(barang);
        Pinjaman_textField.setText(String.valueOf(pinjaman));
        JatuhTempo_FormattedTextField.setText(jatuhTempo);
        Keterangan_TextArea.setText(keterangan);
        NilaiTaksir_textField.setText(String.valueOf(taksir));
    }

    private void NamaBarang_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaBarang_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaBarang_textFieldActionPerformed

    private void NamaPenggadai_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPenggadai_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPenggadai_textFieldActionPerformed

    private void Kontak_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kontak_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kontak_textFieldActionPerformed

    private void JatuhTempo_FormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JatuhTempo_FormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JatuhTempo_FormattedTextFieldActionPerformed

    private void TanggalGadai_FormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalGadai_FormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalGadai_FormattedTextFieldActionPerformed

    private void Pinjaman_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pinjaman_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pinjaman_textFieldActionPerformed

    private void NilaiTaksir_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NilaiTaksir_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NilaiTaksir_textFieldActionPerformed

    private void Simpan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpan_btnActionPerformed
        String nama = NamaPenggadai_textField.getText();
        String kontak = Kontak_textField.getText();
        String namaBarang = NamaBarang_textField.getText();
        String taksir = NilaiTaksir_textField.getText();
        String pinjaman = Pinjaman_textField.getText();
        String tanggalGadai = TanggalGadai_FormattedTextField.getText();
        String jatuhTempo = JatuhTempo_FormattedTextField.getText();
        String keterangan = Keterangan_TextArea.getText();

        if (nama.isEmpty() || namaBarang.isEmpty() || pinjaman.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi data wajib!");
            return;
        }

        try (Connection conn = new controller.Koneksi().koneksi()) {
            if (idTransaksi == -1) {
                // MODE TAMBAH
                String sql = "INSERT INTO transaksi (nama_penggadai, kontak, nama_barang, nilai_taksir, jumlah_pinjaman, tanggal_gadai, jatuh_tempo, keterangan, status) " +
                             "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                try (PreparedStatement ps = conn.prepareStatement(sql)) {
                    ps.setString(1, nama);
                    ps.setString(2, kontak);
                    ps.setString(3, namaBarang);
                    ps.setDouble(4, model.RupiahHelper.parse(taksir));
                    ps.setDouble(5, model.RupiahHelper.parse(pinjaman));
                    ps.setString(6, tanggalGadai);
                    ps.setString(7, jatuhTempo);
                    ps.setString(8, keterangan);
                    ps.setString(9, "Digadaikan");

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan.");
                }
            } else {
                // MODE EDIT
                String sql = "UPDATE transaksi SET nama_penggadai = ?, kontak = ?, nama_barang = ?, nilai_taksir = ?, jumlah_pinjaman = ?, jatuh_tempo = ?, keterangan = ? WHERE id = ?";
                try (PreparedStatement ps = conn.prepareStatement(sql)) {
                    ps.setString(1, nama);
                    ps.setString(2, kontak);
                    ps.setString(3, namaBarang);
                    ps.setDouble(4, Double.parseDouble(taksir));
                    ps.setDouble(5, Double.parseDouble(pinjaman));
                    ps.setString(6, jatuhTempo);
                    ps.setString(7, keterangan);
                    ps.setInt(8, idTransaksi);

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Transaksi berhasil diperbarui.");
                }
            }

            new DaftarTransaksi().setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
        }
    }//GEN-LAST:event_Simpan_btnActionPerformed

    private void Batal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Batal_btnActionPerformed
        new DaftarTransaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_Batal_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInputTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInputTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInputTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInputTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInputTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal_btn;
    private javax.swing.JFormattedTextField JatuhTempo_FormattedTextField;
    private javax.swing.JTextArea Keterangan_TextArea;
    private javax.swing.JLabel Keterangan_txt;
    private java.awt.TextField Kontak_textField;
    private javax.swing.JLabel Kontak_txt;
    private java.awt.TextField NamaBarang_textField;
    private javax.swing.JLabel NamaBarang_txt;
    private java.awt.TextField NamaPenggadai_textField;
    private javax.swing.JLabel NamaPenggadai_txt;
    private javax.swing.JLabel Nama_txt5;
    private java.awt.TextField NilaiTaksir_textField;
    private javax.swing.JLabel NilaiTaksir_txt;
    private java.awt.TextField Pinjaman_textField;
    private javax.swing.JLabel Pinjaman_txt;
    private javax.swing.JButton Simpan_btn;
    private javax.swing.JLabel TambahTransaksi;
    private javax.swing.JFormattedTextField TanggalGadai_FormattedTextField;
    private javax.swing.JLabel TanggalGadai_txt;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
